### ISSUE TITLE
Documentation on Firmware

### ISSUE THREAD

**Issue by sn00pster** [MaJerle/ESP_AT_Lib#10]
Hi,

The documentation could do with a bit more of a hint/warning about the firmware that people have on their device, it absolutely requires the official firmware from ESP to work properly (I couldn't get the http server working, so spent ages figuring out how to flash the ESP firmware on it)

After flashing, the HTTP server works correctly.    While bits may work fine with the AI-THINKER firmware not all of it will as I found out!

**Comment by MaJerle** [comment]
http://majerle.eu/documentation/esp_at/html/page_faq.html

**Comment by sn00pster** [comment]
I think it could do with being repeated here:

http://majerle.eu/documentation/esp_at/html/page_update_at_software.html#sect_update_process_preparations

and more importantly in the readme.md

I missed the FAQ...I suspect others might too.

**Comment by MaJerle** [comment]
Now I added new event, which is triggered if ESP AT software version is less than minimum supported by library. Check examples, main.c files.

**Comment by sn00pster** [comment]
Cool, always best to make it as explicit as possible what's required!
