### ISSUE TITLE
CWMODE autoconnect is always send but ESP_AT 1.7.5 does not support

### ISSUE THREAD

**Issue by jondurrant** [MaJerle/ESP_AT_Lib#101]
Using ESP-01S with Oct-21 release of ESP_AT 1.7.5 (would have liked 2.2 but only have 1M). 1.7.5 gives an error if autoconnect option is on CWMODE
e.g. AT+CWMODE=1,1
Option required to remove the autoconnect. Unsure if that will cause any resilience issues within lwesp.

**Comment by MaJerle** [comment]
Min AT version, to support all features, is as per info below. I can understand this problem, then.
You can customize lwesp and remove this parameter.

https://github.com/MaJerle/lwesp/blob/2442493803c5ea4eb4c468e4d2e48fbf8e4975ec/lwesp/src/include/lwesp/lwesp_opt.h#L756-L764

**Comment by jondurrant** [comment]
Thanks. So to be clear. The library is being targeted at 2.2.0?

**Comment by MaJerle** [comment]
Library targets to follow official releases of ESP-AT w/ latest releases.
I'm not always "up-to-date" but that's the plan, at least.

**Comment by jondurrant** [comment]
Makes perfect sense. I'll have to get brave and replace the flash chip on my ESP-01S;-)
