### ISSUE TITLE
MQTT over SSL

### ISSUE THREAD

**Issue by jondurrant** [MaJerle/ESP_AT_Lib#108]
I required MQTT over SSL so that there is a degree of protection on network. (Not investigated certificate authentication, yet).  

Local fork of code to allow extension of: lwesp_mqtt_client_info_t to include ssl booling flag, and lwesp_mqtt_client_connect to use LWESP_CONN_TYPE_SSL.

I believe you have plans to look at TLS/SSL management, which makes sense. Happy to share my fudge.

**Comment by MaJerle** [comment]
Is this a message that you have done it or you are seeking for solution?

For the moment, I have no implementation for secure TCP, but with mbedTLS it is a long term plan.

\ref LWESP_CONN_TYPE_SSL is still not perfect, as attack can be still executed locally on UART pins.
Best is to do everything on MCU internally, from ecoding and decoding.

This includes another layer of TCP connection, similar to altcp in LwIP stack.

**Comment by jondurrant** [comment]
I've made the changes, so code is available (https://github.com/jondurrant/lwespFork)

Security concerns  right now would be in network penetration. If you have got into my home and have the device in your hand I think I have bigger problems;-)

**Comment by MaJerle** [comment]
Could you create a pull request of your changes?

**Comment by jondurrant** [comment]
Yes of course.

**Comment by jondurrant** [comment]
Pull created, though can't work out how to link to issue

**Comment by MaJerle** [comment]
I see it. It needs coding style improvementa first, then it can be merged.

Thanks for proposing.

**Comment by jondurrant** [comment]
I will leave that with you as not sure what coding standards you are
working too.

Jon
