### ISSUE TITLE
Missing lwesp_sys_template.c?

### ISSUE THREAD

**Issue by bmkuter** [MaJerle/ESP_AT_Lib#111]
Reading through the porting guide, I should see a template for filling in my system functions, `lwesp/src/system/lwesp_sys_template.c`? Has that been deprecated? Same question with the template folder missing here: `lwesp/src/include/system/port/template/*`

**Comment by MaJerle** [comment]
Seems odd, indeed.

I suggest you take already existing port (win32, or cmsis, or freertos) and adjust it for your needs.

Which arch do you use?

**Comment by bmkuter** [comment]
I was planning on using MQX from NXP.

**Comment by MaJerle** [comment]
> I was planning on using MQX from NXP.

This one is technically unknown to me. I know it exists but I have no understanding of its API. Sorry, you will have to manually implement it.

**Comment by bmkuter** [comment]
Thanks! Your FreeRTOS template should help
