### ISSUE TITLE
wifi easy connect

### ISSUE THREAD

**Issue by sumanclimote** [MaJerle/ESP_AT_Lib#114]
Does this lib support the "wifi easy connect", I am interested to make a IOT system with this:
https://www.wi-fi.org/discover-wi-fi/wi-fi-easy-connect
https://www.wi-fi.org/download.php?file=/sites/default/files/private/Wi-Fi_Easy_Connect_Specification_v2.0.pdf

**Comment by MaJerle** [comment]
Library supports what ESP AT supportes. I am not sure this is there.

**Comment by sumanclimote** [comment]
Perfect I just opened a ticket to check it, link for the same for reference - 
https://github.com/espressif/esp-at/issues/622
