### ISSUE TITLE
I found that lwesp cannot send data

### ISSUE THREAD

**Issue by xzxzhao** [MaJerle/ESP_AT_Lib#119]
I found that lwesp cannot send data when there are many threads in the system, the specific reason has not been located

**Comment by MaJerle** [comment]
Unfortunately this does not provide enough information. In my experience, system with 18 threads operates well - case on my side.

There may be several reasons, for instance:
- Other threads have absolutely higher priority and do not block to let other threads execution
- You are in cooperation mode w/o thread block and other threads never jump out
- Missuse of LwESP API code - for instance locking the core from one thread and forget to unlock it?
