### ISSUE TITLE
What's the meaning of LwESP's Process Thread?

### ISSUE THREAD

**Issue by niedong** [MaJerle/ESP_AT_Lib#120]
Hi @MaJerle . I'm a little bit confused about what's role LwESP's Process Thread has played in.

[The document](https://docs.majerle.eu/projects/lwesp/en/latest/user-manual/inter-thread-comm.html) says that LwESP uses two threads, one is producing and one is processing. But producing thread is the one that actually process the message, e.g. call `lwespi_initiate_cmd`, wait for `sem_sync`, and release the `sem` for the API to continue (if in blocking mode). Is this some kind of function naming misfit? Meanwhile, the document refers Process Thread as the one that release `sem_sync` and process each character.

![image](https://user-images.githubusercontent.com/37202664/191487799-efd84fa1-fed7-4923-8c36-e307ca7ee34e.png)

![image](https://user-images.githubusercontent.com/37202664/191488739-f7c3ebcc-587b-4c52-86bf-8e6a624d1142.png)

But isn't the User Process Thread that actually does so? (a.k.a `lwesp_input_process`). I don't see any character-processed behavior by LwESP's Process Thread.

So it seems that LwESP's Process Thread has no significant purpose and can be removed? Or is this some document conflicts or error? 

Thanks!

**Comment by MaJerle** [comment]
Depends on configuration. Process thread handles timeouts (always) and in case of using buffer with lwesp_input function, it processes the data from buffer. 

When you use lwesp_input_process, process thread is only to run timeouts.

See this part here

https://github.com/MaJerle/lwesp/blob/52b90298fba29c556ec69f4ea2506ca5b7f7c1bb/lwesp/src/lwesp/lwesp_threads.c#L211
