### ISSUE TITLE
Broke lwesp_ll_stm32.c driver for f4 and f7 MCUs

### ISSUE THREAD

**Issue by tommasoclini** [MaJerle/ESP_AT_Lib#135]
In commit 290280d, line 220 of lwesp_ll_stm32.c was changed, this broke the driver for f4 and f7 MCUs.
This change was probably done to support h7 MCUs.

**Comment by MaJerle** [comment]
https://github.com/MaJerle/lwesp/commit/b3c07d8161780492c087c78df0bd4da2af87ada5

**Comment by tommasoclini** [comment]
Perfect, thanks
