### ISSUE TITLE
Bad connection type sending to ESP while choose UDP

### ISSUE THREAD

**Issue by MichalPeterek** [MaJerle/ESP_AT_Lib#18]
https://github.com/MaJerle/ESP_AT_Lib/blob/0483db2c75871eded50972084927875da5c07ded/src/esp/esp_int.c#L1733

**Comment by MaJerle** [comment]
Fixed. https://github.com/MaJerle/ESP_AT_Lib/commit/41a558878114217300fd43f522aa559b3e2f5eb6
