### ISSUE TITLE
Semaphore（sem_sync ） multiple meaningless calls

### ISSUE THREAD

**Issue by zhangxichao** [MaJerle/ESP_AT_Lib#26]
Hi MaJerle:

In Esp.c File:

    /* Create threads */
    esp_sys_sem_wait(&esp.sem_sync, 0);         /* ①*/
    if (!esp_sys_thread_create(&esp.thread_producer, "esp_producer", esp_thread_producer, &esp.sem_sync, ESP_SYS_THREAD_SS, ESP_SYS_THREAD_PRIO)) {
        esp_sys_sem_release(&esp.sem_sync);     /* Release semaphore */
        goto cleanup;
    }
    esp_sys_sem_wait(&esp.sem_sync, 0);         /* ② */
    if (!esp_sys_thread_create(&esp.thread_process, "esp_producer", esp_thread_process, &esp.sem_sync, ESP_SYS_THREAD_SS, ESP_SYS_THREAD_PRIO)) {
        esp_sys_sem_release(&esp.sem_sync);     /* Release semaphore */
        goto cleanup;
    }
    esp_sys_sem_wait(&esp.sem_sync, 0);         /* ③ */
    esp_sys_sem_release(&esp.sem_sync);         /* Release semaphore */

①：A sem_sync lock is obtained,If the producer thread is created successfully 
②：It will try to get the lock again,If the process thread is created successfully，But no one released the lock，So will this lock fail?
③：try to get the lock again，Fail?

And in the producer thread, why continue to acquire this lock?

I'm puzzled. Please give me some advice. Thank you.

**Comment by zhangxichao** [comment]
/* Create threads */
esp_sys_sem_wait(&esp.sem_sync, 0);         /* ①*/
if (!esp_sys_thread_create(&esp.thread_producer, "esp_producer", esp_thread_producer, &esp.sem_sync, ESP_SYS_THREAD_SS, ESP_SYS_THREAD_PRIO)) {
    esp_sys_sem_release(&esp.sem_sync);     /* Release semaphore */
    goto cleanup;
}
esp_sys_sem_wait(&esp.sem_sync, 0);         /* ② */
if (!esp_sys_thread_create(&esp.thread_process, "esp_producer", esp_thread_process, &esp.sem_sync, ESP_SYS_THREAD_SS, ESP_SYS_THREAD_PRIO)) {
    esp_sys_sem_release(&esp.sem_sync);     /* Release semaphore */
    goto cleanup;
}
esp_sys_sem_wait(&esp.sem_sync, 0);         /* ③ */
esp_sys_sem_release(&esp.sem_sync);         /* Release semaphore */

①：A sem_sync lock is obtained,If the producer thread is created successfully
②：It will try to get the lock again,If the process thread is created successfully，But no one released the lock，So will this lock fail?
③：try to get the lock again，Fail?

And in Line 89 to 91 of Esp_threads.c File，
the producer thread, why continue to acquire this lock?

**Comment by MaJerle** [comment]
I don't see your line numbers, anyway, last wait and release is not necessary, but it is also not a fail. Code works as expected, no bugs here.

**Comment by zhangxichao** [comment]
Well, I just didn't notice that the thread entry unlocked the semaphore.
But what's the meaning of Marker ③ and why?
And in Line 89 to 91 of Esp_threads.c File，
the producer thread, why continue to acquire this lock?

the  wait and Release of Marker ③ and the wait of Line 89 to 91 of Esp_threads.c, 
Can these three statement be removed?

**Comment by MaJerle** [comment]
I don't know what lines 89-91 are, sorry. In my case these are semaphore create, by last commit. Can you please clarify what are you interested?

if you are interested in:

    esp_sys_sem_wait()
    esp_sys_sem_release();

Then answer is no. It cannot be removed as we have to wait first to thread to unlock semaphore. Once this happens, we will pass wait function but then since noone else will release semaphore, we have to do it manually.

**Comment by zhangxichao** [comment]
Line 89 ~ 91 is:

            ESP_CORE_UNPROTECT();
            esp_sys_sem_wait(&e->sem_sync, 0);
            ESP_CORE_PROTECT();

**Comment by zhangxichao** [comment]
Why wait for threads to release semaphores in order to ensure that threads are running?

**Comment by MaJerle** [comment]
@zhangxichao, Why would be fail to acquire lock again? Semaphores are used to sync threads. One thread is waiting another to finish. This is happening in esp_threads.c.

**Comment by zhangxichao** [comment]
Hi,MaJerle
Why not put 
        ESP_CORE_UNPROTECT();
        esp_sys_sem_wait(&e->sem_sync, 0);
        ESP_CORE_PROTECT();
after Mark ③?

**Comment by MaJerle** [comment]
For further discussion, open new issue and download latest changes first.
