### ISSUE TITLE
Communicate with STM32

### ISSUE THREAD

**Issue by snahmad** [MaJerle/ESP_AT_Lib#3]
Hi,

I have STM32 Firmware running with CAN stack. 

I have esp8286 Wifi Module attached to STM32 32. 
How can I run web server on STM32 and communcate with  esp8286  using AT commands.

Have you tried out?

**Comment by MaJerle** [comment]
shahmad, this library communicates with ESP via AT commands.

**Comment by snahmad** [comment]
ok, thanks.
