### ISSUE TITLE
Minor issue with debug types.

### ISSUE THREAD

**Issue by Crypth** [MaJerle/ESP_AT_Lib#31]
https://github.com/MaJerle/ESP_AT_Lib/blob/6e922d7d5d49295503be80d4fe4698391e827187/src/include/esp/esp_debug.h#L79

`#define ESP_DBG_TYPE_ALL            (GSM_DBG_TYPE_TRACE | GSM_DBG_TYPE_STATE)   /*!< All debug types */`

probably a remnant from GSM lib, likely to be:

`#define ESP_DBG_TYPE_ALL            (ESP_DBG_TYPE_TRACE| ESP_DBG_TYPE_STATE)   /*!< All debug types `

**Comment by MaJerle** [comment]
Thanks for reporting. Fixed in https://github.com/MaJerle/ESP_AT_Lib/commit/7b319bee53f86a74ab8732689fd174e6140ba23b
