### ISSUE TITLE
esp_netconn_close() crashes

### ISSUE THREAD

**Issue by ev-ermakov** [MaJerle/ESP_AT_Lib#32]
Hello,

In `esp_netconn_close()`  (esp_netconn.c on lines 697-698):

```c
    esp_conn_set_arg(conn, NULL);               /* Reset argument */
    esp_conn_close(conn, 1);                    /* Close the connection */
```

Meanwhile, in `netconn_evt()` on lines 178-185:

```c
        case ESP_EVT_CONN_RECV: {
            esp_pbuf_p pbuf;

    (1)     nc = esp_conn_get_arg(conn);        /* Get API from connection */
            pbuf = esp_evt_conn_recv_get_buff(evt); /* Get received buff */

            esp_conn_recved(conn, pbuf);        /* Notify stack about received data */
    (2)     nc->rcv_packets++;                  /* Increase number of received packets */
            ...
```

Suppose there is a connection to a host that is actively transmitting data to us (i. e. with a high bit rate). If the `esp_netconn_close()` function is called at this moment, the program will crash.

Screenshots: exception and stack trace.

![a](https://user-images.githubusercontent.com/22344340/52168457-b5bdfb00-277e-11e9-9951-75f45ddea89c.png)
![b](https://user-images.githubusercontent.com/22344340/52168459-bbb3dc00-277e-11e9-96f5-4c4a1cabaa3e.png)

**Comment by MaJerle** [comment]
Thanks for reporting. Commit 8368226c3fc54c902c23dd6082c56397ebbb0068 should fix the issue.

**Comment by ev-ermakov** [comment]
Thank you. The program no longer crashes.
