### ISSUE TITLE
esp_config.h - Missing?

### ISSUE THREAD

**Issue by Korporal** [MaJerle/ESP_AT_Lib#36]
There is a header file named "esp_config.h" that's referred to by other files [here](https://github.com/MaJerle/ESP_AT_Lib/blob/master/src/include/esp/esp_includes.h) but it isn't present anywhere in the folder hierarchy, did I do something wrong or is this an oversight?

Thanks

**Comment by MaJerle** [comment]
You have to create this file. Please have a look here: https://majerle.eu/documentation/esp_at/html/page_appnote.html#sect_config
