### ISSUE TITLE
too many  ESP_CORE_PROTECT calls  ,cause dead lock

### ISSUE THREAD

**Issue by kelvinhwp** [MaJerle/ESP_AT_Lib#4]
ESP_CORE_PROTECT();                     /* Protect core */
        res = espi_process(data, len);          /* Process input data */
        ESP_CORE_UNPROTECT();   

        espi_process(data,len) ->   may callback esp_reset(),    then dead lock happen.

**Comment by MaJerle** [comment]
@kelvinhwp, you should read documentation.

http://majerle.eu/documentation/esp_at/html/group___e_s_p___s_y_s.html

**Comment by kelvinhwp** [comment]
this happens when first poweron 8266 , rcv"ready", then call reset , RTOS dead lock. 
ps. the code is upate.

**Comment by kelvinhwp** [comment]
ok,i got it . nucleous os has not  recursive mutex ,and semaphore can has the same effect?
