### ISSUE TITLE
ESP8266 DHCP support

### ISSUE THREAD

**Issue by reeduschung** [MaJerle/ESP_AT_Lib#43]
Hi MaJerle,

You're doing well, could you add DHCP feature (AT+CWDHCP command) for station wifi mode?

Thank for your time.

**Comment by MaJerle** [comment]
@reeduschung I have added it now. It is under esp_dhcp.c file.
it has also been implemented that before every `AT+CIPSTA_CUR` IP reading, `AT+CWDHCP_CUR?` command is called to get new and updated DHCP status.

To always get up-to-date IP information, focus on `ESP_EVT_WIFI_IP_ACQUIRED` event, which is called each time IP reading is done. Function `esp_sta_copy_ip` has a new parameter which gives you `is_dhcp` status.
