### ISSUE TITLE
ESP_32 support

### ISSUE THREAD

**Issue by Masi2017** [MaJerle/ESP_AT_Lib#44]
Hi All,

I was wondering if library supports esp_32 WROOM? I tried to set the ESP_CFG_ESP32 to 1 and  ESP_CFG_ESP8266 to 0 to be able to use the library for ESP32 but I've received an error at the compile time. In esp_config_default.h it's mentioned that ESP_CFG_ESP32 must be set to 0, so does this mean that library doesn't support ESP32?
Also I should mention that when I set get time and date request I am getting the following format which is not compatible with the current parser :
![image](https://user-images.githubusercontent.com/34062463/62306337-b0045200-b44f-11e9-8aff-db2997e4a01c.png)

I've added the following code in (espi_parse_cipsntptime.c before "msg->msg.tcpip_sntp_time.dt->date = espi_parse_number(&str);" ) and problem is resolved:
    if (*str == ' ') str++;

**Comment by MaJerle** [comment]
For now yes.

**Comment by Masi2017** [comment]
Hi Sorry I didn't get that what do you mean by yes? It does support? But I can't enable that.

**Comment by MaJerle** [comment]
For now it does not support.

**Comment by Masi2017** [comment]
OK thanks

**Comment by MaJerle** [comment]
Informarion I have is that Espressif thinks to made ESP8266 and ESP32 comnands compatible. So far this is not the case, some commands accept different parameters, like CWDHCP, for example.

Once migration is done, library will support both. Put yourself to watch list and you will be notified.
