### ISSUE TITLE
ESP_CFG_DBG_OFF undefined in http server header file

### ISSUE THREAD

**Issue by tvandergeer** [MaJerle/ESP_AT_Lib#49]
See here: https://github.com/MaJerle/ESP_AT_Lib/blob/develop/esp_at_lib/src/include/esp/apps/esp_http_server.h#L60

Should this be ESP_DBG_OFF ?

**Comment by MaJerle** [comment]
Yes. This HTTP server was more for demo purpose and not for true usage. Please consider using netconn API for server instead.

**Comment by tvandergeer** [comment]
Ok, any recommendations for HTTP protocol library on top of the netconn API?

My use case is a basic configuration page using a phone or desktop browser as client.

**Comment by MaJerle** [comment]
Example here https://github.com/MaJerle/ESP_AT_Lib/blob/develop/snippets/netconn_server.c
