### ISSUE TITLE
Incorrect tick calculations

### ISSUE THREAD

**Issue by sn00pster** [MaJerle/ESP_AT_Lib#7]
I noticed in your port for cmsis that you often time the number of ticks that it took to complete the operation on queues, however, you have assigned the type as uint32_t, this will produce an incorrect value when the tick overflows and should actually be a signed calculation.

**Comment by MaJerle** [comment]
No, why signed? On overflow we will have negative time. This is wrong.

**Comment by sn00pster** [comment]
Sorry, brain is tired.  I was thinking of something else!
